---
title: "Simcoin multi-run Report"
date: '`r format(Sys.time(), "%d %B, %Y")`'
author: "simcoin"
output:
  pdf_document:
    pandoc_args:
      - -V
      - classoption=twocolumn
    toc: yes
  html_document:
    toc: yes
---

```{r knitr_options, include=FALSE}
library(knitr)

knitr::opts_chunk$set(
  fig.path='RmdFigs/',
  warning=FALSE,
  message=FALSE,
  error = TRUE,
  echo = FALSE,
  dev = 'pdf',
  fig.align='center'
  )

# set working directory for development: knitr::opts_knit$set(root.dir = '/tmp/multi-run/')
```

```{r setup, include=FALSE}
library(jsonlite)
library(anytime)
library(dplyr)
library(kableExtra)
library(lattice)
Sys.setenv(TZ='UTC')

general_infos <- fromJSON(file('run-1/general_infos.json'))
tick_infos    <- read.csv2("tick_infos.csv", dec=".")

txs    <- read.csv2("txs.csv", dec=".")
blocks <- read.csv2("blocks.csv", dec=".")
tips   <- read.csv2("tips.csv", dec=".")


blocks_received <- read.csv2("blocks_received.csv", dec=".")
txs_received    <- read.csv2("blocks_received.csv", dec=".")

tx_exces    <- read.csv2("tx_exceptions.csv", dec=".")
block_exces <- read.csv2("block_exceptions.csv", dec=".")
rpc_exces   <- read.csv2("rpc_exceptions.csv", dec=".")

args      <- stream_in(file('args.json'))
sim_start <- tick_infos$start[1]
```

## Simulation
```{r read_start_arguments}
args_transposed <- as.data.frame(t(args))
kable(args_transposed, col.names = c('value'), format = 'latex', caption ='Start arguments') %>%
  kable_styling(latex_options = c('scale_down','HOLD_position'))
```

```{r simulation}
step_times           <- data.frame(t(data.frame(general_infos$step_times)))
colnames(step_times) <- c('timestamp')
step_times           <- step_times[order(step_times$timestamp), , drop = FALSE]

diff_steps <- data.frame(diff(as.matrix(step_times)))
diff_steps <- rbind(diff_steps, apply(diff_steps, 2, sum))
diff_steps$duration_min <- diff_steps$timestamp/60
diff_steps <- diff_steps %>% mutate_at(.vars = vars(timestamp, duration_min), .funs = funs(round(.,2)))
rownames(diff_steps)   <- c('preparation step', 'run step', 'postprocessing step (wo. report creation)', '***total***')

#kable(diff_steps, align = c('ll'), col.names = c('duration [s]', 'duration [min]'), format = 'latex') %>%
#  kable_styling(latex_options = c('scale_down','HOLD_position'))

#TODO merge general_infos.json
```

## System

```{r system_information}
kable(Sys.info(), col.names = c('value'), format = 'latex', caption = 'System information') %>%
  kable_styling(latex_options = c('scale_down','HOLD_position'))
```

```{r system_hardware_specs}
infos <- data.frame(c(general_infos$cpu_model, general_infos$cpus, round(as.double(general_infos$total_memory) / 1000000, 3)))
row.names(infos) <- c('CPU model', 'CPU(s)', 'memory [GB]')
kable(infos, col.names = c('value'), format = 'latex', caption = 'System hardware specs') %>%
  kable_styling(latex_options = c('scale_down','HOLD_position'))
```

## Overall stats

```{r ticks}
mins <- aggregate(tick_infos$timestamp, by=list(tick_infos$tag), FUN=min)
colnames(mins) <- c('tag', 'run_start')

ticks         <- merge(tick_infos, mins)
ticks$elapsed <- ticks$timestamp - ticks$run_start 
```

```{r tick_duration_summary}
kable(unclass(summary(tick_infos$duration)), col.names = c('duration [s]'), digits = 3, caption = 'Overall tick duration', format = 'latex')  %>%
  kable_styling(latex_options = c('HOLD_position'))
```

### Blocks

```{r block_propagation_summary}
kable(unclass(summary(blocks_received$propagation_duration * 1000)), col.names = c('propagation [ms]'), digits = 3, caption = 'Overall block propagation', format = 'latex') %>%
  kable_styling(latex_options = c('HOLD_position'))
```

```{r block_size_summary}
kable(unclass(summary(blocks$total_size / 1000)), col.names = c('size [kB]'), digits = 3, caption = 'Overall block size', format = 'latex') %>%
  kable_styling(latex_options = c('HOLD_position'))
```

### Transactions

```{r txs_propagation_summary}
kable(unclass(summary(txs_received$propagation_duration * 1000)), col.names = c('propagation [ms]'), digits = 3, caption = 'Overall transactions propagation', format = 'latex') %>%
  kable_styling(latex_options = c('HOLD_position'))
```

```{r txs_per_block_summary}
kable(unclass(summary(blocks$txs)), digits = 0, caption = 'Overall transactions per block', format = 'latex') %>%
  kable_styling(latex_options = c('HOLD_position'))
```


### Nodes

```{r tips}
kable(tips, format = 'latex') %>%
  kable_styling(latex_options = c('scale_down','HOLD_position'))
not_active_tips <- tips[!(tips$status=='active'),]
```

\clearpage

```{r tick_duration_xyplot, fig.cap='Tick duration over time', fig.env='figure*'}
xyplot(tick_infos$duration ~ ticks$elapsed, groups=ticks$tag, xlab = 'Time [s]', ylab = 'Duration [s]', t='b' )
```

```{r tick_duration_median, fig.cap='Tick duration', fig.env='figure*'}
boxplot(tick_infos$duration ~ tick_infos$tag)
```

```{r blocks}
blocks$total_size_kb <- blocks$total_size/1000
```

```{r stale, fig.cap='Stale blocks', fig.env='figure*'}
stale_blocks <- blocks[blocks$stale == "Stale", ]
stale_blocks <- aggregate(timestamp~stale+tag, data=stale_blocks, FUN=length)
colnames(stale_blocks)[3] <- "count" # counted the number of timestamps for blocks
boxplot(stale_blocks$count ~ stale_blocks$tag)
```

```{r block_size_bloxplot, fig.cap='Block size', fig.env='figure*'}
boxplot(blocks$total_size ~ blocks$tag)
```

\clearpage

#### R and package versions used

```{r sessionInfo, include=TRUE, echo=TRUE, results='markup'}
devtools::session_info()
```
